name: Build ImmortalWRT Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull ImmortalWRT ImageBuilder
      run: |
        docker pull immortalwrt/imagebuilder:x86-64-openwrt-24.10.0

    - name: Generate package list
      run: |
        grep 'CONFIG_PACKAGE_' .config | sed 's/CONFIG_PACKAGE_//g' | sed 's/=y//g' > package_list.txt

    - name: Build firmware
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          immortalwrt/imagebuilder:x86-64-openwrt-24.10.0 \
          sh -c 'make image PROFILE=generic FILES=/workspace/soft PACKAGES="$(cat package_list.txt)"'

    - name: Upload firmware to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: bin/targets/x86/64/
