name: Build ImmortalWRT Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull ImmortalWRT ImageBuilder
      run: |
        docker pull immortalwrt/imagebuilder:x86-64-openwrt-24.10.0

    - name: List files in workspace for debugging
      run: |
        ls -al /home/runner/work/buildimmortalwrt/buildimmortalwrt

    - name: Build firmware
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace \
          immortalwrt/imagebuilder:x86-64-openwrt-24.10.0 \
          make image PROFILE=generic FILES=/workspace/soft PACKAGES=$(cat .config | grep CONFIG_PACKAGE_ | sed 's/CONFIG_PACKAGE_//g' | sed 's/=y//g')

    - name: Upload firmware to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: bin/targets/x86/64/
